from board import Board, move

b = Board()

b.make_move(move("a2a3"))
b.make_move(move("e7e5"))
b.make_move(move("h2h4"))
b.make_move(move("f8a3"))
b.make_move(move("f2f4"))
b.make_move(move("e5f4"))
b.make_move(move("e2e3"))
b.make_move(move("f4e3"))
b.make_move(move("b2b4"))
b.make_move(move("a3c1"))
b.make_move(move("a1a6"))
b.make_move(move("b7a6"))
print(b.to_fen())
if False:
    b.make_move(move("a"))
    b.make_move(move("a"))
    b.make_move(move("a"))
    b.make_move(move("a"))
    b.make_move(move("a"))
    b.make_move(move("a"))
    b.make_move(move("a"))
    b.make_move(move("a"))
    b.make_move(move("a"))
    b.make_move(move("a"))
    b.make_move(move("a"))
    b.make_move(move("a"))
    b.make_move(move("a"))
    print(b.to_fen())
